- name: リポジトリのインストール
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: zabbix-agentのインストール
  yum:
    name: zabbix-agent

- name: zabbix-server情報を設定
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - ServerActive=db
    - Server=db
